### ISSUE TITLE
Store json configuration file path to .flubu file

### ISSUE THREAD

**Issue by SixGoesNine** [dotnetcore/FlubuCore#261]
Would it be possible that json configuration file path is stored in .flubu file? This would solve that path to the file wouldn't needed to be passed through `-cf `option every time when it is different than flubusettings.json

**Comment by mzorec** [comment]
Yes it could be done. I am not planing on doing this feature myself anytime soon as I have quite alot of other tasks in queue. So if you or anyone else would be willing to do a PR that would be great. 

Implementation details can be discused on gitter so we don't spam others.

**Comment by SixGoesNine** [comment]
Ok I'll try to implement it myself. 

I see 2 posibilities how we could implement this

1. When you run `flubu setup` you would get 3 options:
    1 - Set script location
    2 - Set project file location
    3 - Set configuration file location

    and if you would choose 3 you could add or update configuration file location in .flubu location

2. You could just run `flubu setup -cf=pathToFile`

Which option do you prefer? Maybe some other suggestions?

**Comment by mzorec** [comment]
First I would implement that flubusettings.json file is searched at [default script directories ](https://github.com/dotnetcore/FlubuCore/blob/155053a42c95496f5530febf5c8dbfcd264014ac/src/FlubuCore/Scripting/BuildScriptLocator.cs#L13) and not only on the root directory. 

Personally I like first option more because I think it's more intuitive but in the end you could implement both options.  So yeah I would accept PR with implemented option 1 or if you implement both options. If you also implement second option don't forget to add help
