### ISSUE TITLE
FlubuCore Setup - Directories and files suggestions

### ISSUE THREAD

**Issue by mzorec** [dotnetcore/FlubuCore#292]
In `flubu setup` suggestions for directories and file names should be added similar as in Flubu interactive mode when typing cd command. 

- When entering script location only .cs files should be suggested
- When entering csproj location only .csproj files should be suggested
- When entering .json(configuration file)  location only .json files should be suggested.

**Comment by huanlin** [comment]
one idea has been crossed my mind: maybe `flubu setup` can help the user a little bit for .csproj file , like this:
```
Enter path to script file (.cs) (enter to skip): Build/BuildScript.cs
Is 'Build/Build.csproj' your build project? [Y]es/[N]o: 
```
after the use entered .cs file, flubu checks if there is a .csproj file at location of the .cs file (no need for recursive searching), if there is one and only one csproj file, then ask the user is it your build project, otherwise ask user the location of .csproj file.

Answering Yes: take that .csproj file.
Answering No: ask user the location of .csproj file.

**Comment by mzorec** [comment]
Sounds good. Alternative to yes/no is that the csproj locations is offered as a hint. If user press enter hinted csproj file is accepted. Otherwise if user start's typing hint disapears. Not sure what would be better :) 

Hints in interactive mode:

![image](https://user-images.githubusercontent.com/6092976/78857511-da200200-7a29-11ea-85b7-7421eedec776.png)

**Comment by huanlin** [comment]
> Sounds good. Alternative to yes/no is that the csproj location is offered as a hint. If user press enter hinted csproj file is accepted. Otherwise if user start's typing hint disapears. Not sure what would be better :)
> 
> Hints in interactive mode:
> 
> ![image](https://user-images.githubusercontent.com/6092976/78857511-da200200-7a29-11ea-85b7-7421eedec776.png)

Cool! Yes, that's even better! Hint+1
